title: Nikolai Slavov
description: Personal reflections from Prof. Nikolai Slavov. Ideas and discussions about practicing science and systems biology

url: https://nikolai.slavovlab.net
paginate_path: "page:num/"
permalink: :title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 6

navigation:
  - title: Bio
    url: /bio
  - title: Blog
    url: /index.html
  - title: PTI
    url: https://www.parallelsq.org


social:
  github: nslavov
  twitter: slavov_n
  facebook: nslavov
  linkedin: nslavov

google_analytics: "UA-4005755-5"


theme: jekyll-theme-cayman
