title: Nikolai Slavov
description: "Nikolai Slavov, Professor at Northeastern University and Director of Parallel Squared Technology Institute. Ideas and discussions about the scientific process, systems biology, building and managining organizations."

url: https://nikolai.slavovlab.net
paginate_path: "page:num/"
permalink: :title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 6

navigation:
  - title: Bio
    url: /bio
  - title: Blog
    url: /
  - title: PTI
    url: https://www.parallelsq.org


social:
  github: nslavov
  twitter: slavov_n
  facebook: nslavov
  linkedin: nslavov

google_analytics: "UA-4005755-5"


theme: jekyll-theme-cayman
